service: serverless-practice

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION, 'eu-central-1'}
  versionFunctions: false
  memorySize: 128 #default to minimum, overwrite in functions, if necessary
  # role: ${env:AWS_LAMBDA_ROLE, 'arn:aws:iam::615663043961:role/lambda'}
  deploymentPrefix: ${self:service}
  tags:
    ENVIRONMENT: ${self:provider.stage}

package:
  individually: true
  exclude:
    - "**/*"

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  api:
    rootPath: 'api'
  webpack:
      includeModules:
        forceExclude:
          - aws-sdk
          - sharp

functions:
  hello-world:
    handler: hello-world/index.handler
    description: 'hello world'
    timeout: 10
    package:
      include:
        - hello-world/**
    events:
      - http:
          path: ${self:custom.api.rootPath}/hello-world
          method: get
          cors: true
